/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package huynhnuhoangyen_1217;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.spec.KeySpec;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESedeKeySpec;
import javax.swing.JOptionPane;
import sun.misc.BASE64Decoder;

/**
 *
 * @author hnhye
 */
public class DeCrypt extends javax.swing.JFrame {
 RSA rsa = new RSA(8);
    BigInteger[] ciphertext = null;
    BigInteger n= null;
    BigInteger d= null;
    /**
     * Creates new form fRSA
     */
    public DeCrypt() {
        this.message = null;
        initComponents();
    }
    SecretKey secretKey;
    byte[] byteCipherText;
    /**
     * Creates new form DeCrypt
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtmahoa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmahoaD3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btngiaimaE1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        messageH2 = new javax.swing.JLabel();
        txtH2 = new javax.swing.JTextField();
        messageM3 = new javax.swing.JLabel();
        txtM3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        btngiaima1 = new javax.swing.JButton();
        btngiaima2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        messageN1 = new javax.swing.JTextField();
        messageM2 = new javax.swing.JTextField();
        messageE1 = new javax.swing.JTextField();
        txtM1 = new javax.swing.JTextField();
        txthash = new javax.swing.JTextField();
        txtbKeyK1 = new javax.swing.JTextField();
        txtkhoaK3 = new javax.swing.JTextField();
        message = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("FORM NHAN");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Mở FILE mã hóa E3");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoFileE3(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cipher(E3):");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Key Encrypt(K3):");

        txtmahoaD3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtmahoaD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmahoaD3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Decrypt(D3):");

        btngiaimaE1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btngiaimaE1.setText("Giải mã E1");
        btngiaimaE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiaimaE1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Tách chuỗi (D3) = M3+M2+N1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTachchuoiD3(evt);
            }
        });

        messageH2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messageH2.setText("Message Hash (H2):");

        messageM3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messageM3.setText("Message(M3):");

        txtM3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Tách chuỗi N1: M2+E1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTachchuoiN1(evt);
            }
        });

        btngiaima1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btngiaima1.setText("Giải mã E3");
        btngiaima1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiMaE3(evt);
            }
        });

        btngiaima2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btngiaima2.setText("Băm chuỗi N1");
        btngiaima2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHash(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Kiểm tra toàn vẹn");

        messageM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageM2ActionPerformed(evt);
            }
        });

        txtkhoaK3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtkhoaK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkhoaK3(evt);
            }
        });

        message.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message.setText("Message(N1):");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Message(M2):");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cipher Message(E1):");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Key Decrypt(K1):");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Message(M1):");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Hash (H2'):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(56, 56, 56)
                        .addComponent(txtmahoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(messageM3)
                            .addComponent(messageH2)
                            .addComponent(jLabel3)
                            .addComponent(message)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmahoaD3, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addComponent(txtkhoaK3)
                            .addComponent(txtM3)
                            .addComponent(txtH2)
                            .addComponent(messageM2)
                            .addComponent(messageE1)
                            .addComponent(messageN1)
                            .addComponent(txtbKeyK1)
                            .addComponent(txtM1)
                            .addComponent(txthash))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btngiaima1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btngiaimaE1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btngiaima2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(278, 278, 278))
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel1)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmahoa)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkhoaK3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmahoaD3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btngiaima1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtM3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageM3)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtH2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageH2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageN1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(message)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageM2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageE1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbKeyK1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtM1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthash, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btngiaimaE1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btngiaima2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoFileE3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoFileE3
        try{
            BufferedReader br = null;
            String fileName = "C:\\Users\\ADMIN\\Desktop\\DuLieuMaHoaE3.txt";
            br = new BufferedReader(new FileReader(fileName));
            StringBuffer sb = new StringBuffer();
            JOptionPane.showMessageDialog(null, "Da  mo file thanh cong");
            char[] ca = new char[5];
            while(br.ready()){
                int len = br.read(ca);
                sb.append(ca,0,len);
            }
            br.close();
            System.out.println("Du lieu la:" + ""+ sb);
            String chuoi = sb.toString();
            txtmahoa.setText(chuoi);
        }catch(IOException ex){
            Logger.getLogger(DeCrypt.class.getName()).log(Level.SEVERE, null, ex) ;
        }
    }//GEN-LAST:event_btnMoFileE3

    private static final String UNICODE_FORMAT="UTF8";
    public static final String DESEDE_ENCRYPTION_SCHEME="DESede";
    private KeySpec myKeySpec;
    private SecretKeyFactory mySecretKeyFactory;
    private Cipher cipher;
    byte[] keyAsBytes;
    private String myEncryptionKey;
    private String myEncryptionScheme;
    SecretKey key;
    
    private void btngiaimaE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiaimaE1ActionPerformed
        try{
//            myEncryptionKey=txtbKeyK1.getText();
//            myEncryptionScheme=DESEDE_ENCRYPTION_SCHEME;
//            keyAsBytes=myEncryptionKey.getBytes(UNICODE_FORMAT);
//            myKeySpec=new DESedeKeySpec(keyAsBytes);
//            mySecretKeyFactory=SecretKeyFactory.getInstance(myEncryptionScheme);
//            cipher=Cipher.getInstance(myEncryptionScheme);
//            key=mySecretKeyFactory.generateSecret(myKeySpec);
//            System.out.println("Khoa ma hoa la: "+" "+key);
//            String plainText=messageE1.getText();
//            String encrypted=decrypt(plainText);
//            System.out.println("Encrypted Value: "+encrypted);
//            txtM1.setText(encrypted);
            String mes = messageE1.getText();
//        messageE1.setText(messageE1);
        ciphertext = rsa.encrypt("hutech");
        StringBuilder bf = new StringBuilder();
        for(int i=0; i < ciphertext.length;i++ )
        {
            bf.append(ciphertext[i].toString(16).toUpperCase());
            if(i!=ciphertext.length - 1)
                System.out.print("");
        }
        System.out.println("kkk" +ciphertext);
        
        String dhash = rsa.decrypt(ciphertext, d, n);
        System.out.println("van ban goc la" +dhash);
        txtM1.setText(dhash);
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btngiaimaE1ActionPerformed

    private void btnTachchuoiD3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTachchuoiD3

        String inputText = txtmahoaD3.getText();
        String[] substrings = inputText.split("-"); 
            txtM3.setText(substrings[3]);
            messageN1.setText(substrings[0] + "-" + substrings[1] );
            txtH2.setText(substrings[2]);
    }//GEN-LAST:event_btnTachchuoiD3

    private void btnTachchuoiN1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTachchuoiN1
        String inputText = messageN1.getText();
        String[] substrings = inputText.split("-");
 
        if (substrings.length >= 2) {
            messageE1.setText(substrings[0]);
           messageM2.setText(substrings[1]);
        }
    }//GEN-LAST:event_btnTachchuoiN1

    
    private void btnGiaiMaE3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiMaE3


            try{
            String cipherText=txtmahoa.getText();
            txtmahoa.setText(cipherText);
            Cipher aesCipher=Cipher.getInstance("AES");
            aesCipher.init(Cipher.DECRYPT_MODE,secretKey,aesCipher.getParameters());
            byte[] byteDecryptedText= aesCipher.doFinal(byteCipherText);
            String strDecryptedText=new String(byteDecryptedText);
            System.out.println("Decrypt Text message is: "+ strDecryptedText);
            txtmahoaD3.setText(strDecryptedText);
        }catch(Exception ex){
            System.out.print("Loi ma hoa: "+ex);
        }

    }//GEN-LAST:event_btnGiaiMaE3

    private void btnHash(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHash
        try{
            String chuoi = "";
            chuoi = messageN1.getText();
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(chuoi.getBytes());
            byte byteData[] = md.digest();
            StringBuffer sb = new StringBuffer();
            for(int i = 0; i < byteData.length; i++){
                sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
            }
            txthash.setText(sb.toString());
            StringBuffer hexString = new StringBuffer();
            for(int i = 0; i < byteData.length; i++){
                String hex = Integer.toHexString(0xff & byteData[i]);
                if(hex.length() == 1){
                    hexString.append('0');
                }
                hexString.append(hex);
            }
            
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_btnHash

    private void messageM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageM2ActionPerformed

    private void txtkhoaK3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkhoaK3
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkhoaK3

    private void txtmahoaD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmahoaD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmahoaD3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeCrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeCrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeCrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeCrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeCrypt().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngiaima1;
    private javax.swing.JButton btngiaima2;
    private javax.swing.JButton btngiaimaE1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel message;
    private javax.swing.JTextField messageE1;
    private javax.swing.JLabel messageH2;
    private javax.swing.JTextField messageM2;
    private javax.swing.JLabel messageM3;
    private javax.swing.JTextField messageN1;
    private javax.swing.JTextField txtH2;
    private javax.swing.JTextField txtM1;
    private javax.swing.JTextField txtM3;
    private javax.swing.JTextField txtbKeyK1;
    private javax.swing.JTextField txthash;
    private javax.swing.JTextField txtkhoaK3;
    private javax.swing.JTextField txtmahoa;
    private javax.swing.JTextField txtmahoaD3;
    // End of variables declaration//GEN-END:variables

    char mahoakt(char c, int k){
        if(!Character.isLetter(c)) return c;
        return (char) ((((Character.toUpperCase(c) - 'A') + k) %26 + 26) % 26 + 'A');
        
    }
    
    private String mahoa(String br, int k){
        String kq = "";
        int n = br.length();
        for (int i = 0; i < n; i++) {
            kq+= mahoakt(br.charAt(i), k);
        }
        return kq;
    }

//    private String decrypt(String encryptedString) {
//        String decryptedString =null;
//        try{
//            cipher.init(Cipher.DECRYPT_MODE,key);
//            BASE64Decoder base64decoder=new BASE64Decoder();
//            
//            byte[] encryptedText=base64decoder.decodeBuffer(encryptedString);
//            byte[] plainText= cipher.doFinal(encryptedText);
//            String a= new String(plainText);
//            System.out.println("Chuoi plainText la: "+a);           
//            decryptedString=a;
//        }catch(Throwable ex){
//            ex.printStackTrace();
//        }
//        return decryptedString;
//    }

    static class Instance {

        static SecretKey secretKey;
        static byte[] byteCipherText;

        public Instance() {
        }
    }
}
